#!/usr/bin/env node
/**
 * generate-skills.mjs — generate SKILLS.md and .well-known/skills.json
 * from the discover-skills walker.
 *
 * Single source of truth: scripts/lib/discover-skills.mjs.
 *
 * Cross-references data/skills-matrix.yaml for promotion_status,
 * instances_using, owner, notes — but the walker output is authoritative
 * about "does this skill actually exist on disk?".
 *
 * Usage:
 *   npm run generate:skills
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";
import os from "node:os";
import { discoverSkills } from "./lib/discover-skills.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");

const workspaceDir = rootDir;
const userDir = path.join(os.homedir(), ".claude");

const { skills, anomalies, totals } = discoverSkills({
  workspaceDir,
  userDir,
  pluginRoot: null, // plugin scan disabled by default
});

// Cross-reference with skills-matrix.yaml
const matrixPath = path.join(rootDir, "data", "skills-matrix.yaml");
const matrix = existsSync(matrixPath)
  ? yaml.load(readFileSync(matrixPath, "utf-8")) || {}
  : { skills: [] };
const matrixById = Object.fromEntries((matrix.skills || []).map((s) => [s.id, s]));

// Merge walker output with matrix data; track unmapped skills (on disk but not in matrix)
const enriched = skills.map((s) => {
  const m = matrixById[s.id] || null;
  return {
    id: s.id,
    source: s.source,
    description: s.frontmatter?.description || "",
    version: s.frontmatter?.version || null,
    owner: m?.owner || (s.source === "workspace" ? "framework" : "external"),
    in_framework: m?.in_framework ?? (s.source === "workspace"),
    promotion_status: m?.promotion_status || (s.source === "workspace" ? "evaluating" : "external"),
    instances_using: m?.instances_using || [],
    has_issues: s.hasIssues,
  };
});

const matrixIds = new Set(Object.keys(matrixById));
const onDiskIds = new Set(skills.map((s) => s.id));
const unmappedOnDisk = [...onDiskIds].filter((id) => !matrixIds.has(id));
const inMatrixOnly = [...matrixIds].filter(
  (id) => !onDiskIds.has(id) && matrixById[id].in_framework === true,
);

// --- Write .well-known/skills.json ---
const skillsJson = {
  schema_version: "1.0",
  generated_at: new Date().toISOString(),
  totals,
  skills: enriched,
  anomalies,
  unmapped_on_disk: unmappedOnDisk,
  in_matrix_but_missing_on_disk: inMatrixOnly,
};

const wellKnownPath = path.join(rootDir, ".well-known", "skills.json");
writeFileSync(wellKnownPath, JSON.stringify(skillsJson, null, 2) + "\n");
console.log(`✓ wrote ${path.relative(rootDir, wellKnownPath)} (${enriched.length} skills)`);

// --- Write SKILLS.md ---
const lines = [];
lines.push("# Skills");
lines.push("");
lines.push("> Auto-generated by `npm run generate:skills` (single source of truth: `scripts/lib/discover-skills.mjs`).");
lines.push("> Cross-referenced with `data/skills-matrix.yaml` for promotion status, instance adoption, and ownership.");
lines.push("");
lines.push(`Last generated: ${skillsJson.generated_at}`);
lines.push("");
lines.push(`**Totals:** ${totals.workspace} workspace · ${totals.user} user · ${totals.plugin} plugin`);
lines.push("");

const byStatus = {
  canonical: enriched.filter((s) => s.promotion_status === "canonical"),
  evaluating: enriched.filter((s) => s.promotion_status === "evaluating"),
  candidate: enriched.filter((s) => s.promotion_status === "candidate"),
  external: enriched.filter((s) => s.promotion_status === "external"),
  other: enriched.filter(
    (s) => !["canonical", "evaluating", "candidate", "external"].includes(s.promotion_status),
  ),
};

for (const [status, group] of Object.entries(byStatus)) {
  if (group.length === 0) continue;
  lines.push(`## ${status.charAt(0).toUpperCase() + status.slice(1)} (${group.length})`);
  lines.push("");
  lines.push("| Skill | Owner | Description | Instances |");
  lines.push("|---|---|---|---|");
  for (const s of group.sort((a, b) => a.id.localeCompare(b.id))) {
    const using = s.instances_using.length ? s.instances_using.join(", ") : "—";
    const desc = (s.description || "").slice(0, 100).replace(/\|/g, "\\|");
    lines.push(`| \`${s.id}\` | ${s.owner} | ${desc} | ${using} |`);
  }
  lines.push("");
}

if (anomalies.length > 0) {
  lines.push("## ⚠ Anomalies");
  lines.push("");
  for (const a of anomalies) {
    lines.push(`- **${a.kind}** (${a.source}): ${a.detail}`);
  }
  lines.push("");
}

if (unmappedOnDisk.length > 0) {
  lines.push("## ⚠ On disk but not in `skills-matrix.yaml`");
  lines.push("");
  unmappedOnDisk.forEach((id) => lines.push(`- \`${id}\``));
  lines.push("");
}

if (inMatrixOnly.length > 0) {
  lines.push("## ⚠ In `skills-matrix.yaml` but missing from disk");
  lines.push("");
  inMatrixOnly.forEach((id) => lines.push(`- \`${id}\``));
  lines.push("");
}

const skillsMdPath = path.join(rootDir, "SKILLS.md");
writeFileSync(skillsMdPath, lines.join("\n"));
console.log(`✓ wrote ${path.relative(rootDir, skillsMdPath)}`);

if (anomalies.length > 0 || unmappedOnDisk.length > 0 || inMatrixOnly.length > 0) {
  console.log(
    `\n  ${anomalies.length} anomalies, ${unmappedOnDisk.length} unmapped on disk, ${inMatrixOnly.length} matrix-only`,
  );
}
